language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - composer install --no-interaction
  - phpcs --config-set ignore_warnings_on_exit 1
  - sed -i 's/curl/banan/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php

script:
  - php vendor/bin/parallel-lint --exclude vendor .
  - phpcs --standard=vendor/magento-ecg/coding-standard/Ecg,vendor/mygento/coding-standard/Mygento-Mage1 --ignore=lib .
  - php vendor/bin/phpcpd --exclude=vendor .
  - php vendor/bin/phpdcd --exclude=vendor .
  - php vendor/bin/phpmd . text vendor/mygento/coding-standard/Mygento-Mage1/phpmd.xml --exclude vendor

