language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - composer install --no-interaction
  - phpcs --config-set ignore_warnings_on_exit 1
  - sed -i 's/curl/banan/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php

script:
  - phpcs --standard=vendor/magento-ecg/coding-standard/Ecg --ignore=vendor .
  - php vendor/bin/parallel-lint --exclude vendor .
  - php vendor/bin/phpcpd --exclude=vendor .
  - php vendor/bin/phpdcd --exclude=vendor .
  - php vendor/bin/phpmd . text codesize --exclude vendor
